-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


DROP TABLE IF EXISTS public.addresses;

CREATE TABLE IF NOT EXISTS public.addresses
(
    id bigint NOT NULL DEFAULT nextval('addresses_id_seq'::regclass),
    city character varying(255) COLLATE pg_catalog."default",
    country character varying(255) COLLATE pg_catalog."default",
    postal_code integer NOT NULL,
    receiver character varying(255) COLLATE pg_catalog."default",
    street character varying(255) COLLATE pg_catalog."default",
    street_nr integer NOT NULL,
    CONSTRAINT addresses_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.cart_item;

CREATE TABLE IF NOT EXISTS public.cart_item
(
    id bigint NOT NULL DEFAULT nextval('cart_item_id_seq'::regclass),
    quantity integer NOT NULL,
    product_id bigint NOT NULL,
    shopping_cart_id bigint NOT NULL,
    CONSTRAINT cart_item_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.login_user;

CREATE TABLE IF NOT EXISTS public.login_user
(
    id bigint NOT NULL DEFAULT nextval('login_user_id_seq'::regclass),
    email character varying(50) COLLATE pg_catalog."default",
    firstlogin timestamp without time zone,
    firstname character varying(255) COLLATE pg_catalog."default",
    isbuyer boolean,
    isseller boolean,
    lastlogin timestamp without time zone,
    lastname character varying(255) COLLATE pg_catalog."default",
    password character varying(255) COLLATE pg_catalog."default",
    phone character varying(20) COLLATE pg_catalog."default",
    username character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT login_user_pkey PRIMARY KEY (id),
    CONSTRAINT ukimbgbrpv0puvgb6ieun7ho2ef UNIQUE (username)
);

DROP TABLE IF EXISTS public.product;

CREATE TABLE IF NOT EXISTS public.product
(
    id bigint NOT NULL DEFAULT nextval('product_id_seq'::regclass),
    description character varying(500) COLLATE pg_catalog."default",
    instock boolean NOT NULL,
    media bytea,
    name character varying(255) COLLATE pg_catalog."default",
    price real NOT NULL,
    product_category_id bigint NOT NULL,
    login_user_id bigint NOT NULL,
    CONSTRAINT product_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.product_category;

CREATE TABLE IF NOT EXISTS public.product_category
(
    id bigint NOT NULL DEFAULT nextval('product_category_id_seq'::regclass),
    category_name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT product_category_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.purchase;

CREATE TABLE IF NOT EXISTS public.purchase
(
    id bigint NOT NULL DEFAULT nextval('purchase_id_seq'::regclass),
    orderdate timestamp without time zone NOT NULL,
    orderstatus boolean NOT NULL,
    totalprice real NOT NULL,
    addresses_id bigint NOT NULL,
    shopping_cart_id bigint NOT NULL,
    login_user_id bigint NOT NULL,
    user_payment_id bigint NOT NULL,
    CONSTRAINT purchase_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.purchase_product;

CREATE TABLE IF NOT EXISTS public.purchase_product
(
    id bigint NOT NULL DEFAULT nextval('purchase_product_id_seq'::regclass),
    product_id bigint NOT NULL,
    purchase_id bigint NOT NULL,
    CONSTRAINT purchase_product_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.reviews;

CREATE TABLE IF NOT EXISTS public.reviews
(
    id bigint NOT NULL DEFAULT nextval('reviews_id_seq'::regclass),
    feedback character varying(500) COLLATE pg_catalog."default",
    review_score integer NOT NULL,
    product_id bigint NOT NULL,
    login_user_id bigint NOT NULL,
    CONSTRAINT reviews_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.roles;

CREATE TABLE IF NOT EXISTS public.roles
(
    id integer NOT NULL DEFAULT nextval('roles_id_seq'::regclass),
    name character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT roles_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.shopping_cart;

CREATE TABLE IF NOT EXISTS public.shopping_cart
(
    id bigint NOT NULL DEFAULT nextval('shopping_cart_id_seq'::regclass),
    is_active boolean NOT NULL,
    login_user_id bigint NOT NULL,
    CONSTRAINT shopping_cart_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.user_addresses;

CREATE TABLE IF NOT EXISTS public.user_addresses
(
    id bigint NOT NULL DEFAULT nextval('user_addresses_id_seq'::regclass),
    defaultaddr boolean,
    addresses_id bigint NOT NULL,
    login_user_id bigint NOT NULL,
    CONSTRAINT user_addresses_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.user_payment;

CREATE TABLE IF NOT EXISTS public.user_payment
(
    id bigint NOT NULL DEFAULT nextval('user_payment_id_seq'::regclass),
    card_nr character varying(16) COLLATE pg_catalog."default" NOT NULL,
    expiry_date character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name_on_card character varying(255) COLLATE pg_catalog."default",
    payment_type character varying(255) COLLATE pg_catalog."default",
    security_code character varying(5) COLLATE pg_catalog."default" NOT NULL,
    login_user_id bigint NOT NULL,
    CONSTRAINT user_payment_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.user_roles;

CREATE TABLE IF NOT EXISTS public.user_roles
(
    user_id bigint NOT NULL,
    role_id integer NOT NULL,
    CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, role_id)
);

ALTER TABLE IF EXISTS public.cart_item
    ADD CONSTRAINT fke89gjdx91fxnmkkssyoim8xfu FOREIGN KEY (shopping_cart_id)
    REFERENCES public.shopping_cart (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.cart_item
    ADD CONSTRAINT fkjcyd5wv4igqnw413rgxbfu4nv FOREIGN KEY (product_id)
    REFERENCES public.product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.product
    ADD CONSTRAINT fkcwclrqu392y86y0pmyrsi649r FOREIGN KEY (product_category_id)
    REFERENCES public.product_category (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.product
    ADD CONSTRAINT fkj084951m1yqhb2ogv8cdip77q FOREIGN KEY (login_user_id)
    REFERENCES public.login_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.purchase
    ADD CONSTRAINT fk1uxosatw94mw8828rat2tngg9 FOREIGN KEY (shopping_cart_id)
    REFERENCES public.shopping_cart (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.purchase
    ADD CONSTRAINT fkcw480bsyj5bdn9r58kdl0dgr8 FOREIGN KEY (login_user_id)
    REFERENCES public.login_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.purchase
    ADD CONSTRAINT fkixjrpa93o8r0aoytx8qwm401g FOREIGN KEY (user_payment_id)
    REFERENCES public.user_payment (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.purchase
    ADD CONSTRAINT fkl9t6xk8x2iy9tmxvt6jcu2s9u FOREIGN KEY (addresses_id)
    REFERENCES public.addresses (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.purchase_product
    ADD CONSTRAINT fk1te3j5efipmc5c19wve8c90qd FOREIGN KEY (purchase_id)
    REFERENCES public.purchase (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.purchase_product
    ADD CONSTRAINT fkl1da8u1v57wry7sunkkgmjr8o FOREIGN KEY (product_id)
    REFERENCES public.product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.reviews
    ADD CONSTRAINT fk5i5893oju60vq6kr6w9efkf0t FOREIGN KEY (login_user_id)
    REFERENCES public.login_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.reviews
    ADD CONSTRAINT fk9yqmlf28ges8c30nj4v4hva7t FOREIGN KEY (product_id)
    REFERENCES public.product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.shopping_cart
    ADD CONSTRAINT fk5vk1uindumk7aby74okn5qrym FOREIGN KEY (login_user_id)
    REFERENCES public.login_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.user_addresses
    ADD CONSTRAINT fk4nv2v3lr8rp6h0k1iffvw54jd FOREIGN KEY (addresses_id)
    REFERENCES public.addresses (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.user_addresses
    ADD CONSTRAINT fko7by26fln1eiy7iivch2clhnf FOREIGN KEY (login_user_id)
    REFERENCES public.login_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.user_payment
    ADD CONSTRAINT fk6uhjto7polnh8t9302lsejf2f FOREIGN KEY (login_user_id)
    REFERENCES public.login_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.user_roles
    ADD CONSTRAINT fkca2hssfb5ito2kpsc2jhk19f7 FOREIGN KEY (user_id)
    REFERENCES public.login_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.user_roles
    ADD CONSTRAINT fkh8ciramu9cc9q3qcqiv4ue8a6 FOREIGN KEY (role_id)
    REFERENCES public.roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;