# docker-compose.yml
version: "3.8"
services:
  frontend:
    image: "my-app:latest"
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/my-app
      - /my-app/node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
