# Pull the base image
FROM node:13.12.0-alpine
# Set the working directory
WORKDIR /my-app
# Copy app dependencies to container
COPY ./package*.json ./
# Add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH
# Install dependencies
RUN npm install --production=false --dev-dependencies

#COPY . /my-app

# Deploy app for local development
CMD npm run api & npm start
# CMD npm start --host 0.0.0.0 --port 3000 --disableHostCheck true