stages: # List of stages for jobs, and their order of execution
  - build
  - test-quality
#  - docker-build
  - test
#  - deploy

include:
   - template: Code-Quality.gitlab-ci.yml

variables: 
  DOCKER_HOST: tcp://docker:2375/

build-job: # This job runs in the build stage, which runs first.
  stage: build
  image: maven:3.8.3-openjdk-17
  script:
    - cd Backend/EcommerceBackend
    - echo "Building the backend jar"
    - mvn clean package -DskipTests
    - echo "Build complete."
  artifacts:
    paths:
      - Backend/EcommerceBackend/target/*.jar
  only:
    refs:
      - develop
      - master

code_quality:
  stage: test-quality
  artifacts:
    paths: [gl-code-quality-report.json]

code_quality_html:
  extends: code_quality
  variables:
    REPORT_FORMAT: html
  artifacts:
    paths: [gl-code-quality-report.html]

#code_quality:
#  image: maven:3-jdk-11
#  stage: test-quality
#  script:
#    - mvn gitlab-code-quality:analyze
#  artifacts:
#    reports:
#      codequality: Backend/EcommerceBackend/target/code-quality-report.json

npm-build-and-test:
  stage: test
  image: node:latest
  script:
    - cd Frontend
    - npm install
    - npm test
  cache:
    paths:
      - /Frontend/node_modules/
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - /Frontend/node_modules/
  only:
    refs:
      - develop
      - master