stages: # List of stages for jobs, and their order of execution
  - build
  #  - docker-build
  - test
#  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375/

build-job: # This job runs in the build stage, which runs first.
  stage: build
  image: maven:3.8.3-openjdk-17
  script:
    - cd Backend/EcommerceBackend
    - echo "Building the backend jar"
    - mvn clean package -DskipTests
    - echo "Build complete."
  artifacts:
    paths:
      - Backend/EcommerceBackend/target/*.jar
  only:
    refs:
      - develop
      - master

npm-build-and-test:
  stage: test
  image: node:latest
  script:
    - cd Frontend
    - npm install
    - npm test
  cache:
    paths:
      - /Frontend/node_modules/
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - /Frontend/node_modules/
  only:
    refs:
      - develop
      - master
#docker-build:
#  image: docker:23.0.3
#  stage: build
#  services:
#    - docker:dind
#  script:
#    - cd Backend/EcommerceBackend
#    - echo "Building the backend image"
#    - docker build -t monday-backend .
#  dependencies:
#    - build-job
