version: "3"

services:
  postgres:
    image: postgres
    container_name: pg-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgpwd1
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data

  backend:
    build:
      context: ../Backend/EcommerceBackend
    image: monday-backend
    container_name: backend
    restart: always
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: pgpwd1
    depends_on:
      - postgres

  db-init:
    build:
      context: ../Backend/EcommerceBackend
      dockerfile: db-script-dockerfile
    image: pg-db-init
    container_name: db-init-script
    depends_on:
      - postgres
      - backend

  db-images-init:
    build:
      context: ../Backend/EcommerceBackend/sql_initialize_db_manager
      dockerfile: db-images-dockerfile
    image: pg-db-images
    container_name: db-images-script
    depends_on:
      - postgres
      - backend
      - db-init

  frontend:
    image: "monday-frontend:dev"
    container_name: frontend-dev
    build:
      context: ../Frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ../Frontend/:/my-app
      - /my-app/node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - postgres
      - backend

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack-pro  # required for Pro
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
      - "127.0.0.1:53:53"                # DNS config (required for Pro)
      - "127.0.0.1:53:53/udp"            # DNS config (required for Pro)
      - "127.0.0.1:443:443"              # LocalStack HTTPS Gateway (required for Pro)
    environment:
      - DEBUG=${DEBUG-}
      - PERSISTENCE=${PERSISTENCE-}
      - LOCALSTACK_API_KEY=5HUpIF1BDc  # required for Pro
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  pg-data:
