INSERT INTO roles(id,name) VALUES(1,'ROLE_USER');
INSERT INTO roles(id,name) VALUES(2,'ROLE_ADMIN');
INSERT INTO login_user(username, email, password, phone, firstname, lastname, isbuyer, isseller) VALUES ('username', 'username@gmail.com', '$2a$10$9cOQijrPNVgUeMzqnSI1PezrYpZ07TwoSnrtxJWK/PSz9jSxAJt8a', 3467867981, 'firstname', 'lastname', true, true);
INSERT INTO shopping_cart(id,login_user_id) VALUES(1,1);
INSERT INTO product_category(id,category_name) VALUES(1,'food');
INSERT INTO product(id,description,instock,name,price,product_category_id) VALUES(1,'super random pizza', true,'pizza', 8, 1);
INSERT INTO product(id,description,instock,name,price,product_category_id) VALUES(2,'super test pizza', true,'pizza', 6, 1);
INSERT INTO product(id,description,instock,name,price,product_category_id) VALUES(3,'random burger', true,'burger', 5, 1);
INSERT INTO product(id,description,instock,name,price,product_category_id) VALUES(4,'random pasta', true,'pasta', 3, 1);
commit;